AWSTemplateFormatVersion: '2010-09-09'
Description: Template to allow access to secrets in AWS Secrets Manager and decryption permissions for KMS keys.

Parameters:
  ExternalRoleArn:
    Type: String
    Description: ARN of the external role to be granted permissions.

  SecretArnList:
    Type: CommaDelimitedList
    Description: List of ARNs for the secrets in Secrets Manager.

  KmsKeysIdList:
    Type: CommaDelimitedList
    Description: List of KMS Key IDs for decryption access.

Resources:
  # IAM Policy to Allow Access to Secrets in AWS Secrets Manager
  SecretManagerAccessPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "SecretManagerAccessPolicy"
      Description: "Allows access to secrets in AWS Secrets Manager"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: !Ref ExternalRoleArn
            Action: "secretsmanager:*"
            Resource: !Ref SecretArnList

  # Secrets Manager Secret Policies
  SecretsManagerSecretPolicies:
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      SecretArn: !Ref SecretArnList
      ResourcePolicy: 
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal: 
              AWS: !Ref ExternalRoleArn
            Action: "secretsmanager:GetSecretValue"
            Resource: !Ref SecretArnList

  # KMS Key Policies for Decryption Permissions
  KmsKeyPolicies:
    Type: AWS::KMS::Key
    Properties:
      KeyId: !Ref KmsKeysIdList
      Policy:
        Version: "2012-10-17"
        Statement:
          - Sid: "Enable Decryption Permissions"
            Effect: "Allow"
            Principal:
              AWS: !Ref ExternalRoleArn
            Action: 
              - "kms:Decrypt"
              - "kms:DescribeKey"
            Resource: "*"
