AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to allow access to AWS Secrets Manager and KMS decryption for a specified role.

Parameters:
  SecretsArnList:
    Type: List<String>
    Description: List of secrets ARNs that need to be shared.

  ExternalRoleArn:
    Type: String
    Description: ARN for the external role accessing the secrets.

  KmsKeysIdList:
    Type: List<String>
    Description: List of KMS key IDs to allow decryption of the secrets.

Resources:
  # IAM Policy for Secret Manager Access
  SecretManagerAccessPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: SecretManagerAccessPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref ExternalRoleArn
            Action: "secretsmanager:*"
            Resource: !Ref SecretsArnList
      Roles:
        - !Ref ExternalRoleArn

  # Attach Policies to Secrets
  SecretPolicies:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateBody: |
        AWSTemplateFormatVersion: '2010-09-09'
        Resources:
          {{#each SecretsArnList}}
          AttachPolicyToSecret{{@index}}:
            Type: AWS::SecretsManager::ResourcePolicy
            Properties:
              SecretId: {{this}}
              ResourcePolicy: !Ref SecretManagerAccessPolicy
          {{/each}}

  # KMS Key Policies for Decryption
  KmsPolicies:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateBody: |
        AWSTemplateFormatVersion: '2010-09-09'
        Resources:
          {{#each KmsKeysIdList}}
          AttachKmsPolicy{{@index}}:
            Type: AWS::KMS::Key
            Properties:
              KeyId: {{this}}
              Policy:
                Version: "2012-10-17"
                Statement:
                  - Sid: EnableDecryptionPermissions
                    Effect: Allow
                    Principal:
                      AWS: !Ref ExternalRoleArn
                    Action:
                      - "kms:Decrypt"
                      - "kms:DescribeKey"
                    Resource: "*"
          {{/each}}
