AWSTemplateFormatVersion: '2010-09-09'
Description: Template to create a VPC peering connection accepter, routes, and security group ingress rules.

Parameters:
  PeeringConnectionId:
    Type: String
    Description: The ID of the VPC peering connection to be accepted.

  RouteTableIds:
    Type: List<String>
    Description: The IDs of the route tables to add the peering routes to.

  PeerCidrBlock:
    Type: String
    Description: The CIDR block of the peer VPC (Provided by deX).

  SecurityGroupRules:
    Type: List<CommaDelimitedList>
    Description: A list of security group rules in the format from_port,to_port,protocol,security_group_id.

Resources:
  # VPC Peering Connection Accepter
  VPCPeeringConnectionAccepter:
    Type: AWS::EC2::VPCPeeringConnection
    Properties:
      VpcPeeringConnectionId: !Ref PeeringConnectionId
      AutoAccept: true
      Tags:
        - Key: Name
          Value: "Accepted deX Peering Connection"

  # Routes for Peering Connection
  PeerRoutes:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateBody: |
        AWSTemplateFormatVersion: '2010-09-09'
        Resources:
          {{#each RouteTableIds}}
          PeerRoute{{@index}}:
            Type: AWS::EC2::Route
            Properties:
              RouteTableId: {{this}}
              DestinationCidrBlock: !Ref PeerCidrBlock
              VpcPeeringConnectionId: !Ref PeeringConnectionId
          {{/each}}

  # Security Group Ingress Rules
  SecurityGroupIngressRules:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateBody: |
        AWSTemplateFormatVersion: '2010-09-09'
        Resources:
          {{#each SecurityGroupRules}}
          IngressRule{{@index}}:
            Type: AWS::EC2::SecurityGroupIngress
            Properties:
              GroupId: {{@this[3]}}  # security_group_id
              FromPort: {{@this[0]}}  # from_port
              ToPort: {{@this[1]}}    # to_port
              IpProtocol: {{@this[2]}}  # protocol
              CidrIp: !Ref PeerCidrBlock
          {{/each}}
