name: dex_actions_pipeline

on:
  push:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      cloudformation: ${{ steps.changes.outputs.cloudformation }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          cloudformation:
            - 'aws/cloudformation/**'

  deploy_static_dags:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.cloudformation == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.S3_ADMIN_AUTOMATION_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.S3_ADMIN_AUTOMATION_SECRET_KEY }}
          aws-region: us-east-1
      - name: Sync DAGs to S3
        run: aws s3 sync ./aws/cloudformation s3://${{ secrets.S3_PUBLIC_ASSETS_BUCKET }}/cloudformation
